CREATE TABLE Torcedor(
	Id INT IDENTITY, 
	Nome VARCHAR(100),
	CONSTRAINT PK_Id_Torcedor PRIMARY KEY(Id)
	)

SELECT * FROM TORCEDOR

INSERT INTO Nome VALUES ('João')
INSERT INTO Nome VALUES ('Jose')
INSERT INTO Nome VALUES ('Lucas')
INSERT INTO Nome VALUES ('Maria')
INSERT INTO Nome VALUES ('Lucia')
INSERT INTO Nome VALUES ('Vivian')
INSERT INTO Nome VALUES ('Vivian')